### ISSUE TITLE
Mod forcibly creates binding to O key everytime doom is booted up.

### ISSUE THREAD

**Issue by ghost** [mmaulwurff/ultimate-custom-doom#16]
I've set up quick commands to O and P to quicksave the game, but after I installed the mod, pressing O now opens Ultimate Custom Doom's menu settings.

I can go into the "customize controls" option and remove the binding, thus being able to use my quick commands again, but when I turn off and turn on the game again, the same problem is there again.

Since ultimate custom doom has an actual entry in the options menu unlike the original, which could only be accessed via a hotkey, I think it would be fine to remove the default keybinds entirely or change them so they don't reset themselves automatically everytime the game is rebooted.

**Comment by mmaulwurff** [comment]
Fixed in bff98bd.
